# dependencies.R

library(tidyr)
library(dplyr)
library(openxlsx)
library(data.table)
library(quanteda)
library(stringr)
library(rainette)
library(kableExtra)
library(shiny)
library(shinyBS)
library(shinyFiles)
library(shinycssloaders)
library(shinydashboard)
library(shinyjs)
library(shinyWidgets)
library(shinythemes)
library(miniUI)
library(tidyverse)
library(quanteda)
library(igraph)
library(ggraph)
library(scales)
library(visNetwork)
library(Matrix)
library(wordcloud2)
library(RColorBrewer)
